### ISSUE TITLE
PHP Deprecated Warning Spam with MediaWiki 1.41

### ISSUE THREAD

**Issue by D3nnis3n** [StarCitizenTools/mediawiki-extensions-TabberNeue#120]
`AH01071: Got error 'PHP message: PHP Deprecated:  Use of Modules must target desktop and mobile. Module name:ext.tabberNeue.mobile.styles was deprecated in MediaWiki 1.41. [Called from MediaWiki\\ResourceLoader\\StartUpModule::getScript in /var/www/vhosts/domain.com/httpdocs/includes/ResourceLoader/StartUpModule.php at line 436] in /var/www/vhosts/domain.com/httpdocs/includes/debug/MWDebug.php on line 386',`

**Comment by alistair3149** [comment]
Will look into that.
