### ISSUE TITLE
Enhancement: Switching tabbers by clicking #tab-tabber-xx URLs 

### ISSUE THREAD

**Issue by ZoruaFox** [StarCitizenTools/mediawiki-extensions-TabberNeue#150]
I've been utilizing the TabberNeue to create tabbed navigation on my MediaWiki site, and it's been working great for embedding different content within the same page using the `<tabbertransclude>` tag. However, I've encountered a limitation when trying to create a more user-friendly progressive navigation experience.

The issue arises when I attempt to use a clickable button with a URL suffix like `#tab-tabber-xx` to switch to a specific tab within a single page. Unfortunately, this functionality is currently not supported, which means that users are required to manually click on the corresponding Tabber to access the next page, rather than being able to simply click a "Next Step" button.

I noticed that the "Header Tabs" extension offers a similar feature through the use of the `{{#switchtablink:Tab name|Link text|Page name}}` parser function, which allows for programmatic switching of tabs. I was wondering if it would be possible to introduce a similar functionality to TabberNeue, enabling the creation of more intuitive and streamlined navigation experiences.

By adding support for a `#switchtablink` parser function (or something similar) to TabberNeue, it would greatly enhance the extension's capabilities and provide developers with more flexibility in designing progressive navigation pages. This would be particularly beneficial for creating guided workflows or multi-step processes where users can easily progress through different stages by clicking on designated buttons.

I understand that implementing such a feature may require some effort, but I believe it would be a valuable addition to the TabberNeue extension. It would align with the goal of providing a powerful and user-friendly tabbed navigation solution for MediaWiki.

Thank you for your time and attention!

P.S. MediaWiki version: 1.39.7

**Comment by alistair3149** [comment]
Will be looking into it.
It is currently not working when the Tabber is on the same page.
