### ISSUE TITLE
Bug with TOC heading switching

### ISSUE THREAD

**Issue by keepersdungeon** [StarCitizenTools/mediawiki-extensions-TabberNeue#156]
Hello,
With latest version 2.2.4, there seems to interfere with the TOC, if you're jumping from one heading to another and there's a heading in the middle that has a <tabber> tag the scrolling on the page stops on it and does not continue to the heading you initially clicked on your TOC

MW 1.41 
tabberneue 2.2.4
PHP 8.1

**Comment by alistair3149** [comment]
Thanks for the report. Do you have a live demo of the example?

**Comment by keepersdungeon** [comment]
Hello @alistair3149 ,
I can't link to my wiki as it's private but the same happens here https://starcitizen.tools/Crusader_Industries
if you jump to 'see also' when the page loads it will stop on 'jurisdiction' (u need to click on 'see also'  a second time to go to the section). Once u're on 'see also' if you try to jump back to 'History', it will stop on 'jurisdiction' as well. 
Switching between heading without tabber seems fine

**Comment by alistair3149** [comment]
Ah that is a bug with the Citizen skin. It is a known issue that is being looked into. Sometimes on longer pages, pure CSS smooth scroll refuses to scroll all the way to the target.

**Comment by keepersdungeon** [comment]
Ah alright, thought it was TabberNeue that was interfering. Thanks for the info!

**Comment by alistair3149** [comment]
On a side note, this should also be patched on Citizen. Since this is resolved, I'm closing the issue now.
