### ISSUE TITLE
Tabs can no longer contain square brackets in their names

### ISSUE THREAD

**Issue by alex4401** [StarCitizenTools/mediawiki-extensions-TabberNeue#158]
Hi,

There seems to be a regression since v1.8.1, introduced in 7f7589999582e56a1dcf0e5af02ba12e6223a17f (feat: add support for nested tabbers in Codex (#95)), that results in the inability to create tabs that contain `]`, `[` in their names. At wiki.gg we're using version v1.9.1 with patches for #151, but I reproduced this bug in the latest v2 version too. We're using legacy, non-Codex tabbers.

## Reproduction
For a page consisting of the following wikitext:
```
<tabber>
a=a|-|
a>=a|-|
a<=a|-|
a[]=a|-|
b=c|-|
]=a|-|
[=a
</tabber>
```
behaviour is as follows:

- In v1.7.5, v1.8.0: all tabs are displayed correctly.
![image](https://github.com/StarCitizenTools/mediawiki-extensions-TabberNeue/assets/33527044/56eaec8e-cea8-4bb3-8ca7-beea66f9096f)
- At 7f7589999582e56a1dcf0e5af02ba12e6223a17f, or in v1.8.1, v1.9.0, v2.2.4: First three tabs render correctly. Name of tab `a[]` is mangled with pieces of tabber DOM leaking inside. Tab `b` is not displayed at all, instead tab `a[]` displays tab `b`'s contents. Tab `]` is mangled in the same way, displaying contents of tab `[`.
![image](https://github.com/StarCitizenTools/mediawiki-extensions-TabberNeue/assets/33527044/5c86ceee-46d0-48fa-862a-f840278e6f04)

## Cause
Seems like the last line of the following breaks the tabs:
```php
		$htmlTabs = preg_replace( '/\\\n/', '', $htmlTabs );
		$htmlTabs = preg_replace( '/\\\*/', '', $htmlTabs );
		$htmlTabs = str_replace( [ '"[', ']"' ], [ '[', ']' ], $htmlTabs );
```
Notably, when the following HTML is generated:
```html
<article class="tabber__panel" data-mw-tabber-title="a&lt;"><p>
a</p></article>
<article class="tabber__panel" data-mw-tabber-title="a[]"><p>
a</p></article>
```
the last replacement removes the double quote after `]`:
```diff
-<article class="tabber__panel" data-mw-tabber-title="a[]"><p>
+<article class="tabber__panel" data-mw-tabber-title="a[]><p>
```

I don't have any context for those three lines, and can't suggest any patches.

(Internal reference for my fellow wiki.gg friends: WIKIDEV-150)

**Comment by alistair3149** [comment]
Thanks for the detailed report. Those lines are probably legacy code that used to get around some of the weird wikitext parsing issue that we faced before, but it should no longer be needed.
