### ISSUE TITLE
Weird tab change behaviour

### ISSUE THREAD

**Issue by ElandaOfficial** [StarCitizenTools/mediawiki-extensions-TabberNeue#167]
## Intro
Hello I have just recently started using your extension.
There is an issue however, I've set everything up and also set `$wgTabberNeueUpdateLocationOnTabChange = false;` (which, to what I come in a second, makes no real difference to the issue at hand), to disable url setting, all nice and well.

## Issue
However, sadly it works less often than I would like it to, as when I click a tab the content changes but the tab highlight does not AND the url still changes too, even though I turned it off, however sometimes after countless reloading it seems to work *sometimes*.
I still haven't figured out the circumstances under which it starts to work, just after different kinds of reloading ect., but I have a suspicion to which I come after what I found.

The debug console in my browser gives me the following issue:
```
ext.tabberNeue.js:119 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at TabberAction.getTabpanel (ext.tabberNeue.js:119:39)
    at new TabberEvent (ext.tabberNeue.js:288:38)
    at eval (ext.tabberNeue.js:654:24)
```

Which is here in the code:
```js
async init( urlHash ) {
    await this.createTabs();
    await this.createHeader();
    await this.createIndicator();
    
    const activeTab = this.tablist.firstElementChild;
    TabberAction.setActiveTab( activeTab );
    TabberAction.updateHeaderOverflow( this.tablist );
    
    setTimeout( () => {
	    const tabberEvent = new TabberEvent( this.tabber, this.tablist );
	    tabberEvent.init();
    }, 0 );
    
    this.tabber.classList.add( 'tabber--live' );
}
```
(if something is different here from the original code, please pardon me I have changed one or two things for debugging purposes)

And here (from TabberEvent constructor):
```js
this.tabber = tabber;
this.tablist = tablist;
this.header = this.tablist.parentElement;
this.tabs = this.tablist.querySelectorAll( ':scope > .tabber__tab' );
this.activeTab = this.tablist.querySelector( '[aria-selected="true"]' );
this.activeTabpanel = TabberAction.getTabpanel( this.activeTab );
this.indicator = this.tabber.querySelector(
	':scope > .tabber__header > .tabber__indicator'
);
```
So basically, for some reason, it doesn't seem to find `this.activeTab = this.tablist.querySelector( '[aria-selected="true"]' );`, printing it in the console leaves me with `null`.
However `this.tablist` is valid in the console, and even has a child with `aria-selected="true"`, so I am not certain what is going on, but I hope it gives you a pointer in the right direction.

Also, when clicking a tab in this state, I get:
```
Blocked aria-hidden on a <article> element because the element that just received focus must not be hidden from assistive technology users.
Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. 
For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
<article class=​"tabber__panel" data-mw-tabber-title=​"replaceRange" id=​"tabber-replaceRange" role=​"tabpanel" tabindex=​"-1" aria-hidden=​"true" aria-labelledby=​"tab-tabber-replaceRange">​…​</article>​
```

## What I tried?
I have, of course, tried different version of these extension, to no avail.
I have also cleared the cache several times, as I thought maybe the script needs to update locally after config changes.
I did also purge the page multiple times, but it doesn't make a difference.

Any of these attempts made no difference, as I could also verify the configuration and scripts ect. where updated in the dev console.

## Version and other Info
<dl>
<dt>MediaWiki</dt>
<dl>1.42.1</dl>
<dt>TabberNeue</dt>
<dl>2.4.0</dl>
<dt>Skin</dt>
<dl>Vector-2022</dl>
<dt>Showcase of the issue</dt>
<dl>https://wikigh.elandasunshine.xyz/w/Extrait/types/replace</dl>
</dl>

~ Elanda

#### Edit
Forgot mentioning my suspicion:
Now, while I am not too versed in JS, is there a possibility that something happens in a timer hence it works sometimes but not always?

#### Edit 2
I have just tried it again in a new tab, it worked the first time but after reloading it stopped working again, so it is "random". (of course, we know what random really is :D)

#### Edit 3
Indeed, my suspicion has turned out correct:
```js
setTimeout( () => {
	const tabberEvent = new TabberEvent( this.tabber, this.tablist );
	tabberEvent.init();
}, 0);
```
If I set timout delay to 100, it works everytime.

**Comment by EamonHeffernan** [comment]
I came across this on a wiki I was on, I opened a pr that may fix this issue. #173
