### ISSUE TITLE
Feature request: custom classes and id

### ISSUE THREAD

**Issue by Thomas-programmiert** [StarCitizenTools/mediawiki-extensions-TabberNeue#183]
I think a decent feature would be that tabbers can be handed classes, id's and even custom data attributes. Right now they are all getting eaten
`<tabber class="custom-tabber-class">`
`<tabber id="custom-tabber-id">`
`<tabber data-custom="custom-tabber-data">`

This would be handy to directly target the tabber with css or javascript (which I often use to replace tab names with images).
The work around so far is to simply wrap the tabber in a div with said classes or id's.
Implementing this feature would make it more user friendly to the common wiki editor who doesn't have an understanding of how css works.

**Comment by alex4401** [comment]
CC-ing myself into here

**Comment by alistair3149** [comment]
I can look into it but I am not sure how to handle it right.
The issue is that the current Tabber syntax isn't very extensible which makes it difficult to support additional feature like this.
To the best of my knowledge, we might have to rewrite the current syntax to support it...

**Comment by alex4401** [comment]
I think the `<tabber class="someclass">` approach (with classes being appended to the main tabber container) should be fine and won't be dodgy with Parsoid. Any sort of wrapping at the moment and custom CSS already assume the user is ready to hack things together, direct class support just drops a level of indirection.

Of course, I'm sure wrappers will still be needed for some customisations, but that won't be affected by supporting direct custom classes.

**Comment by Thomas-programmiert** [comment]
Sent a pull request for this. Tested it on a private server and it works. and literally as I sent it I think that it's too unsafe. The foreach loop for reading in other arguments should probably be limited to data arguments only. like:
`		foreach ( $args as $key => $value ) {
			if ( !str_starts_with( $key, "data" ) ) continue;
			$head .= ' ' . $key . '=\"' . $value . '\"';
		}
`

**Comment by Thomas-programmiert** [comment]
awesome. Looking forward to it. 
Issue can be closed if you want, I'd close it when it's implemented, so we can still talk about it for now.
