### ISSUE TITLE
Duplicate images on mobile view

### ISSUE THREAD

**Issue by aesulus** [StarCitizenTools/mediawiki-extensions-TabberNeue#2]
On the mobile view, any image within a tab that's under a section will get duplicated.

A test page can be found here: https://hololive.wiki/wiki/User:AnatoleSerial/GalleryTest

![image](https://user-images.githubusercontent.com/8322422/132615489-b7a28b54-865a-4780-a548-9d03b22dc08c.png)

**Comment by alistair3149** [comment]
It might be an upstream issue with MobileFrontend, will look into it.

**Comment by GenerationFallout** [comment]
Hello,

We have the same problem on our side: 

![image](https://user-images.githubusercontent.com/68496923/153572847-002ee3cb-4c68-4d03-9ae3-e85b9cb89e37.png)

An example on this page:

https://fallout-wiki.com/Gecko_(Fallout:_New_Vegas)#Gecko

Cordialy

Kims

**Comment by alistair3149** [comment]
Looks fixed on both sites, closing for now

**Comment by aesulus** [comment]
As of TabberNeue 1.7.1, this issue is still recurring.

Example page: https://hololive.wiki/wiki/User:AnatoleSerial/GalleryTest
