### ISSUE TITLE
TabberNeue Changes Page URL

### ISSUE THREAD

**Issue by BlackTARKUS** [StarCitizenTools/mediawiki-extensions-TabberNeue#29]
Whenever a tab element is clicked, the URL updates to include an anchor for the tab—such as BASEPAGENAME/PAGE#TAB NAME. This is undesirable behavior because it breaks the ability to use the browser's "back" functionality to return to the previous page after interacting with Tabber.

**Comment by alistair3149** [comment]
It can be disabled by setting `$wgTabberNeueUpdateLocationOnTabChange` to `false`. It is kept as the default behavior as Tabber previously function like this.

**Comment by BlackTARKUS** [comment]
Thank you very much
