### ISSUE TITLE
Bulleted and numbered lists do not display properly if they are not on the first tab

### ISSUE THREAD

**Issue by aesulus** [StarCitizenTools/mediawiki-extensions-TabberNeue#3]
If a bulleted or numbered list is not on the first tab, then the bullets / numbers themselves do not display properly.

Here's a test page demonstrating this behavior: https://hololive.wiki/wiki/User:Aesulus/TabberNeue_issue_with_lists

For example, if the expected result is:
1. Alice
2. Bob
3. Carol

On Firefox, the actual result is:

Alice
Bob
Carol

On Chromium-based browsers, the actual result is:

- Alice
- Bob
- Carol

**Comment by alistair3149** [comment]
Thanks for the report! Will look into it.

**Comment by aesulus** [comment]
Thanks for the quick response, Alistair! I'd like to add that I tested this on Mozilla Firefox; however, I just discovered that the behavior on Chromium-based browsers is a bit different.

On Chromium-based browsers, bulleted lists will display on both Desktop and Mobile views but numbered lists will turn into bulleted lists if they're not on the first tab. I've edited my issue to reflect this.

**Comment by alistair3149** [comment]
Sorry for the late response, have been busy with other stuff recently. Would you mind to confirm if the latest patch fix the issue for you?
