### ISSUE TITLE
Tabbers in floating containers get sized as if to contain all tabs at once

### ISSUE THREAD

**Issue by alex4401** [StarCitizenTools/mediawiki-extensions-TabberNeue#34]
Hello! We've recently (April 27th) switched on the ARK Survival Evolved Wiki (which I'm an administrator of) hosted on wiki.gg from the old Gamepedia-developed Tabber extension to TabberNeue. Vector skin is used, with modifications via on-site CSS and some provided by the platform. The issue is present with site CSS disabled, and on a clean MediaWiki install with completely unmodified Vector.

We noticed an issue with tabbers inside `float` containers in some articles, for example: https://ark.wiki.gg/wiki/Obelisk?oldid=466169#Location. Initially, this was going to be about the tabs going off-screen, but that has been addressed (we're using 1.6.1 at the moment) in 8ab7b8330d15c1c15fef8d30d9aea2286dd7bd2f which is now backported via site CSS. I'm guessing the original issue is related though.

With the patch `float` does not have any visible effects if the cumulative width of all tabs is higher than parent's. Even in a scenario where all tabs are sized uniformly, a single tab's content width seems to be the total width of all tabs in the tabber i.e. more than enough to house any tab's content.

Screenshot showing the issue:
![image](https://user-images.githubusercontent.com/33527044/176220110-d3220b2c-b73b-45a5-b735-99344d5727bd.png)

Sandbox on live wiki: https://ark.wiki.gg/wiki/User:Alex4401/test?oldid=473015#constant_size_image,_single
Sandbox on a test wiki (with no wiki.gg modifications): https://ark-wcmove-sandbox.mglolenstine.xyz/wiki/Tabber_issue_test_02#Extinction-0

**Comment by alistair3149** [comment]
Thanks for the report, I'll look into it

**Comment by alistair3149** [comment]
So I looked into the issue and it is the intended behavior.

`float` is operating as expected. However, the issue lies with the width of the whole `<tabber>` element.
The `<tabber>` element will automatically fill all the available width because there are no width defined.
Therefore, setting a width for the `<tabber>` element or its container will make `float` work as expected.

**Comment by alex4401** [comment]
>  The <tabber> element will automatically fill all the available width regardless of its contents.

The behaviour we're seeing is a little different than that - it scales in a direct relation to its contents: when within a float container, it doesn't stretch to all available width like it does outside float. It seems to stretch as if to display the tabs side-by-side, all at once. And after all, with just a single tab the tabber does seem to float just right (top part of the screenshot). It's just when there's more tabs it goes bad.

The sandboxes aren't really going to show it on 1080p and below, now that I think of it.

I'm guessing that's an effect of grid-auto-columns with unrestricted parent width, so a workaround is not worth the complication. Thank you, I'll look into setting up max-widths.
