### ISSUE TITLE
Feature request: Wikitext for tab name or otherwise style the tab name text?

### ISSUE THREAD

**Issue by Fyren** [StarCitizenTools/mediawiki-extensions-TabberNeue#35]
A wiki I contribute to color codes a lot of text using a template that wraps text in a `span` and uses the article path to pick between different colors.  Specifically, if it helps explain, doing something like `{{color|1|some text}}` where the `1` is a color code will maybe color the given text red for the article `Foo/1` or `Foo/2` but blue for `Bar/3` or `Bar/4`.  A user wanted to use our template as part of a tab name, but TabberNeue doesn't pass the given value to be parsed and uses it as plain text.  

Is parsing the tab name as wikitext reasonable?  I guess this would also allow things like putting images in the tab header, but I wouldn't be surprised if there'd be output that doesn't make sense to stick inside the HTML TabberNeue generates for the tabs.

Is there any other reasonable way to style portions of the text?

**Comment by alistair3149** [comment]
> Is parsing the tab name as wikitext reasonable?
Is there any other reasonable way to style portions of the text?

It is possible to parse the tab name but it would cause performance issues that is not worth it if you want to style the text. You can always target the tab names with CSS since they all have unique `id` attributes assigned.

**Comment by Fyren** [comment]
I did specify potions of the name because they wanted to do something like `foo {{color|1|bar}} baz` and not style the whole thing.  Would passing the tab name to be parsed as wikitext have significant overhead compared to if the same text were just straight inside the article?

**Comment by alistair3149** [comment]
I will explore adding a config to allow wikitext parsing in tab header.
There will be additional overhead but I don't have a measurement for now.
