### ISSUE TITLE
CSS Tooltips within Tabber

### ISSUE THREAD

**Issue by BlackTARKUS** [StarCitizenTools/mediawiki-extensions-TabberNeue#36]
The wiki I contribute to uses CSS tooltips to remind users of common information using hover text. Because tabber uses overflow: hidden, these tooltips get clipped when they appear near to any edge of a tabber section. 

Is it at all possible to work around this and allow the tooltips to display properly? Pictured below are 2 images; one without and one with Tabber.

![image](https://user-images.githubusercontent.com/11951612/176897468-cf1d5ae9-7ca0-4931-b776-a545c537f504.png)
 
![image](https://user-images.githubusercontent.com/11951612/176897532-113a2a69-c920-473c-b22c-9bab78d91950.png)

**Comment by alistair3149** [comment]
Sorry for the late response.
You can kind of hack the tooltip with different CSS hacks such as the [position:fixed hack](https://stackoverflow.com/a/45030989) on the tooltips by targeting the tooltip class within tabber (e.g. `.tabber CSSCLASS`). Please let me know if it works for you!
