### ISSUE TITLE
Tabbers within collapsible tables do not display their contents when the table is expanded

### ISSUE THREAD

**Issue by aesulus** [StarCitizenTools/mediawiki-extensions-TabberNeue#4]
If a tabber is within a collapsible table, and the table starts out collapsed, then the contents within the tabs will not display when the table is expanded. The tab contents only show up after one clicks on a tab header.

A test page demonstrating this behavior has been set up here: https://hololive.wiki/wiki/User:Aesulus/TabberNeue_issue_with_collapsible_tables

**Comment by alistair3149** [comment]
Thanks for the report. I'll look into it!

**Comment by alistair3149** [comment]
Didn't know GitHub would auto close the issue. Please feel free to reopen the issue if you run into the same error again!
