### ISSUE TITLE
Hash navigation causes visual display issues in nested tabbers

### ISSUE THREAD

**Issue by alex4401** [StarCitizenTools/mediawiki-extensions-TabberNeue#41]
Hello again from the ARK Survival Evolved Wiki. We unfortunately have to use tabbers nested three levels deep total to display creature spawning maps for a recent DLC map. Switching a tab in one of the depth-3 tabbers and refreshing the page causes depth-2 layout to be miscalculated, obscuring a number of tabs in the depth-2 tabber. The depth-3 tab also becomes visible, but depth-2 header is not updated - guessing state goes rogue.

Using Firefox 102 on Linux. Not seeing this problem on Edge - it switches only the relevant tabber, and no mangling happens.

Repro URL: https://ark.wiki.gg/wiki/Raptor#Asgard-2

Screencast showing the problem:

[Peek 2022-07-22 21-31.webm](https://user-images.githubusercontent.com/33527044/180514347-6a8e07cc-f730-4855-8131-9fab7845b6bd.webm)

Tabbers with max depth of 2 work just fine: https://ark.wiki.gg/wiki/Seeker#Asgard-1

**Comment by alex4401** [comment]
Sorry, we've upgraded to 1.7.2 today and this appears to be resolved.

**Comment by alistair3149** [comment]
No worries. Thanks for letting me know!
