### ISSUE TITLE
In nested tabbers, indentation before {{!}}-{{!}} inserts unwanted <pre></pre> node.

### ISSUE THREAD

**Issue by aesulus** [StarCitizenTools/mediawiki-extensions-TabberNeue#46]
Observed in TabberNeue v1.7.2.

With nested tabbers, we indent to increase readability. However, adding whitespace before lines that begin with `{{!}}-{{!}}` causes TabberNeue to insert an unwanted `<pre></pre>` node in the _max(n - 1, 1)_ subtab, where _n_ is the first subtab that contains leading indentation before `{{!}}-{{!}}`.

For example,

```
<div style="float:right;width:290px;border:1px solid black;padding:5px;text-align:center">
<tabber>
|-|First =
 {{#tag:tabber|
 {{!}}-{{!}} 1 = A content
 {{!}}-{{!}} 2 = B content
 {{!}}-{{!}} 3 = C content
 }}
|-|Second =
 {{#tag:tabber|
 {{!}}-{{!}} 1 = D content
 {{!}}-{{!}} 2 = E content
 {{!}}-{{!}} 3 = F content
 }}
</tabber>
</div>
```

results in this:

![TabberNeue indentation bug](https://user-images.githubusercontent.com/8322422/184503241-1177262b-0126-40da-8a4e-5ba4f81894dc.png)

**Comment by alistair3149** [comment]
It is unfortunately a MediaWiki default behavior to register whitespace as pre. I'm not sure whether it is appropriate to change that behavior as it would not align with MW parsing and additional parsing would be needed, which could come with performance hit. I'm not the expert on MW parser so someone might have a better understanding than I do.

However, to make the wikitext more readable, you can also use comment blocks `<!-- -->` as indents and spacers.

**Comment by aesulus** [comment]
I see. But, we've been indenting nested tabbers for months and this wasn't an issue until recently.

**Comment by alistair3149** [comment]
> I see. But, we've been indenting nested tabbers for months and this wasn't an issue until recently. We know there are versions of TabberNeue where this bug doesn't happen.

It is probably from #27. The performance impact of using `recursiveTagParseFully()` is too costly so we ended up dropping it.

**Comment by aesulus** [comment]
Okay. Well, in that case, don't forget to update [the documentation](https://www.mediawiki.org/wiki/Extension:TabberNeue#Nested_tabbers).

**Comment by alex4401** [comment]
Check if replacing the spaces with tabulators helps. We use them on my wiki sometimes for indents inside templates, and it doesn't seem to render the code blocks.
