### ISSUE TITLE
Contents of nested tabs are truncated by the height of one tab header

### ISSUE THREAD

**Issue by aesulus** [StarCitizenTools/mediawiki-extensions-TabberNeue#5]
Hi, it's me again. I just wanted to start this off by saying many of the editors at Hololive Fan Wiki love TabberNeue. Keep up the good work!

Anyways, nested tabs work well except for the fact that they are truncated by the height of one tab header. The tabs only display properly after one clicks on a top-level tab header.

A test page demonstrating this behavior has been set up here: https://hololive.wiki/wiki/User:Aesulus/TabberNeue_issue_with_nested_tabs

**Comment by alistair3149** [comment]
Glad that you love it and thanks for reporting the issue! I'm currently out of town so I won't be able to fix the issues until next week.

**Comment by fw25** [comment]
This issue can easily be fixed
Download the adaptation from https://wiki.webemotion.nl/media/extension/TabberNeue_adaptation_1.0_based_on_1.1.0.zip

**Explenation**
TabberNeue calculates the height of the tab based on the static content. This causes problems in the case of dynamic content.
To this end, the **$wgTabberNeueHeight** parameter has been added in the modified version.
- $wgTabberNeueHeight="false"; the calculated height is not used
- $wgTabberNeueHeight="true"; the calculated height is used. If the parameter is not specified then this is the default value. 
For an example see https://wiki.webemotion.nl/index.php?title=Sjabloon:Extension:TabberNeue
You can translate the page by selecting the preferred language in the footer

**Comment by alistair3149** [comment]
Should be fixed with 2d4d4121fd77e6d6877cd44e6ce2d2907da1922e

**Comment by fw25** [comment]
Hi,

I have installed the new version and it works great except for Safari 15.4
I only shows the content of the first tab.

With kind regards,

	Felix Wagemakers

**Comment by fw25** [comment]
Hi,

Safari 15.4, MacOS 12.3.1 Monterey, Mac mini M1
Example: https://www.ghklandvanthorn.nl/index.php?title=Publicaties

IOS(iPhone 15.4.1 and iPad 15.3.1) works

With kind regards,

	Felix Wagemakers

**Comment by fw25** [comment]
Hallo,

When testing with 1.4.0 on Safari 15.4 the following error occurs:
Warning: Illegal string offset 'name' in /var/www/vhosts/ghklandvanthorn.nl/httpdocs/includes/registration/ExtensionProcessor.php on line 232

With 1.3.1 there is no error

With kind regards,

	Felix Wagemakers
