### ISSUE TITLE
MD5 hash key appending to ID attribute makes maintaining anchor links difficult.

### ISSUE THREAD

**Issue by Kiokurashi** [StarCitizenTools/mediawiki-extensions-TabberNeue#6]
I would like to ask that this MD5 key be an optional setting. On the wiki I am working on we have links to specific tabs, and having to change any links to include the random hash substring anytime we change the content or just making a link to a new set is an unneccesary frustration.

**Comment by alistair3149** [comment]
Hi there. I am busy at the moment but I will add an option to disable the MD5 key into the extension. The reason behind adding MD5 is that the original Tabber has issues with duplicating tab names, sadly I am not versed enough in PHP and MediaWiki to find an solution to mitigate that.

**Comment by Kiokurashi** [comment]
The option to disable will be fine.
I kinda figured that the purpose of the hash was specifically because of the duplicated tab names.

**Comment by alistair3149** [comment]
The config is added now. Thanks for the suggestions! Please feel free to re-open the ticket if you run into any issue related.

**Comment by Kiokurashi** [comment]
Hello, I am messaging you again to inform you that I have no idea how your toggle works. I've put the `$wgTabberNeueEnableMD5Hash` key in the `**LocalSettings.php**` file, as per the standard, and set it to false, but the extension still adds in the hash string onto the end.

Also, side note: if I'm reading your code correctly then you are append two dashes onto the ID for the tab prior to the Hash key. First at the declaration of the hash, and second at the declaration of the ID. Also means that the ID will always have that dash as well.
