### ISSUE TITLE
Cargo Dynamic Table Styling Broken Within Tabber

### ISSUE THREAD

**Issue by BlackTARKUS** [StarCitizenTools/mediawiki-extensions-TabberNeue#68]
[On this page](https://www.dustloop.com/w/KF4/Weapons#Ranged_Weapon_Stats), dynamic table formatted queries are being used within tabbers.

The first set of tabbers containing tables works as expected. The second set of tabbers, the one labeled "Ranged Weapon Stats", causes the styling and controls of the table to break when accessing the "Level 2" and "Level 3" tabs.

![image](https://user-images.githubusercontent.com/11951612/195904569-65450c3c-0b51-4532-a976-6d69957e7259.png)
![image](https://user-images.githubusercontent.com/11951612/195904583-6d48df55-f5ab-42b2-ac03-19220b0d3d9d.png)

**Comment by alistair3149** [comment]
It seems to be an upstream issue with how Cargo attach the datatable header.
I need to look more into it but I am not sure if it is something that can be fixed on our end.
