### ISSUE TITLE
No tab text displayed

### ISSUE THREAD

**Issue by AlPha5130** [StarCitizenTools/mediawiki-extensions-TabberNeue#73]
When using `<tabbertransclude>` tag, the output tab buttons don't have any texts inside.

After examing the code, I found that the JS side tries to get button text from `data-title` property of generated `<article>`s, but on PHP side there are no property named `data-title` added, only the old `title` property.

So this should be a bug? Modifying PHP side is sufficient.

**Comment by alistair3149** [comment]
Yes it is a bug, will fix it tomorrow

**Comment by alistair3149** [comment]
Thanks for the PR. It should be fixed now
