### ISSUE TITLE
Removing unwanted space under each tab.

### ISSUE THREAD

**Issue by Ranzuu** [StarCitizenTools/mediawiki-extensions-TabberNeue#82]
Hello there I have some issue with unwanted space under the tab with the tabber. 

Whole tabber is limited in height so you can scroll it and not see the items on the whole page (and more) is used.
I understand that you can remove that height limitation, but that will show it on whole page and I don't really want that.
The most big (in height) table will be seen as "max-height" and rest of the tables in the tabber will be big accordingly.

According to my little knowledge it's not possible to remove those spaces left under smaller tables on media wiki (or css). I might be wrong tho.
Do You have some solution to this? To remove them, or to make tabber stop scrolling when selected that tab?

Example page with that issue:
https://wiki.chromerivals.net/index.php?title=Test_Page

Attached Example Image:
![image](https://user-images.githubusercontent.com/66495944/219063972-8058b837-c4c6-4f51-a2f7-14d2b4b1b83e.png)

**Comment by alex4401** [comment]
Have you considered swapping that `height` to a `max-height`, and throwing your custom rules onto `.tabber__panel` instead?
```css
.tabber__panel {
  max-height: 770px;
  overflow-y: auto;
}
```

**Comment by Ranzuu** [comment]
> Have you considered swapping that `height` to a `max-height`, and throwing your custom rules onto `.tabber__panel` instead?
> 
> ```css
> .tabber__panel {
>   max-height: 770px;
>   overflow-y: auto;
> }
> ```

Ah, I did not considered it ;-;. That works like a charm. Space removed. Thank you very much Alex!
