### ISSUE TITLE
Tabbers not displaying correctly on some pages

### ISSUE THREAD

**Issue by VortexArto** [StarCitizenTools/mediawiki-extensions-TabberNeue#96]
TabberNeue is displaying incorrectly on some pages of my wiki. Sometimes they show up correctly, but other times they only show up as an unclickable gray bar. Our SREs have confirmed that it's an upstream issue.

Example URLs:
https://www.avid.wiki/AVID:Community_Portal
https://www.avid.wiki/AVID:Site_Staff

Example Images:
![image](https://github.com/StarCitizenTools/mediawiki-extensions-TabberNeue/assets/139555929/a1b13277-1b07-4ac8-bd62-b35a938f7ccf)
![image](https://github.com/StarCitizenTools/mediawiki-extensions-TabberNeue/assets/139555929/ac295e12-50f7-4efb-9eb6-bd94b5beaf60)

**Comment by alistair3149** [comment]
It is a caching issue since there's a ResourceLoader package name change, clearing out the cache should fix it

**Comment by VortexArto** [comment]
Seems to have been fixed. Thank you for your response
